# Generated by Django 4.1.7 on 2023-04-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytube_account', '0003_alter_mytubeaccount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('thumbnail', models.ImageField(upload_to='videos/')),
                ('mt_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytube_account.mytubeaccount')),
            ],
        ),
    ]
