# Generated by Django 4.1.7 on 2023-05-18 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_remove_video_dislikes_remove_video_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='disliked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
