# Generated by Django 4.1.7 on 2023-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_remove_video_dislikes_remove_video_likes_evaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
