# Generated by Django 4.1.7 on 2023-05-24 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
