# Generated by Django 4.1.7 on 2023-06-02 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_comment_datetime_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='datetime_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
