# Generated by Django 4.1.7 on 2023-06-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_remove_evaluate_datetime_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='calls',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
