# Generated by Django 4.1.7 on 2023-03-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTubeAccount',
            fields=[
                ('id', models.CharField(default=uuid.UUID('3f41395c-342f-4923-b9ba-f84e043a0d52'), editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profile_picture', models.ImageField(default='prof_pictures/default.png', upload_to='prof_pictures/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
