# Generated by Django 4.1.7 on 2023-04-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytube_account', '0002_alter_mytubeaccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytubeaccount',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
